name: Train / Run Salary Model

on:
  workflow_dispatch:
    inputs:
      run_mode:
        description: 'train or run'
        required: false
        default: 'train'
  schedule:
    - cron: '0 1 1 * *'

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyspark boto3 pandas pyarrow

      - name: Run main pipeline
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
        run: |
          set -e

          RUN_MODE="${{ github.event.inputs.run_mode }}"
          RUN_MODE="${RUN_MODE:-train}"

          S3_BUCKET_NAME="${S3_BUCKET_NAME}"
          S3_PREFIX="processed"

          INPUT_PATH="s3a://${S3_BUCKET_NAME}/${S3_PREFIX}/jobs_fact/"
          MODEL_PATH="s3a://${S3_BUCKET_NAME}/models/salary_prediction_model"

          echo "ðŸ”¹ MODE = $RUN_MODE"
          echo "ðŸ”¹ INPUT = $INPUT_PATH"
          echo "ðŸ”¹ MODEL = $MODEL_PATH"

          python main.py \
            --mode "$RUN_MODE" \
            --input-path "$INPUT_PATH" \
            --model-path "$MODEL_PATH" \
            --endpoint "${S3_ENDPOINT:-}" \
            --region "${AWS_REGION:-}"
